app_name: neo's api server
server:
  http:
    port: 9000
    readtimeout: 15
    writetimeout: 15
    idletimeout: 15
    maxheaderbytes: 1024
  grpc:
    port:

logging:
  level: info

auth:
  access_token:
    secret: my-special-secret
    expiration: 10m
    audience: www.myapp.com
    issuer: my-app
  refresh_token:
    secret: my-special-secret
    expiration: 10080m
    audience: www.myapp.com
    issuer: my-app
